import { Product } from './product.model';

export type ShoppingListStatus = 'ACTIVE' | 'COMPLETED' | 'ARCHIVED';

export interface ShoppingListItem {
  id: string;
  product: Product;
  requiredQuantity: number;
  stockQuantity: number;
  missingQuantity: number;
  purchasedQuantity?: number;
  unit: string;
  unitSymbol?: string;
  checked: boolean;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ShoppingList {
  id: string;
  name: string;
  startDate?: string;
  endDate?: string;
  status: ShoppingListStatus;
  statusLabel?: string;
  totalItemsCount: number;
  checkedItemsCount: number;
  completionPercentage: number;
  items: ShoppingListItem[];
  createdAt: string;
  updatedAt: string;
}

export interface GenerateShoppingListRequest {
  name?: string;
  startDate?: string;
  endDate?: string;
}

export interface AddShoppingItemRequest {
  productId: string;
  quantity: number;
  unit?: string;
}

export interface UpdateShoppingItemRequest {
  quantity?: number;
  purchasedQuantity?: number;
  checked?: boolean;
}
