package fr.trollgun.optimiam.shopping.api.dto;

import fr.trollgun.optimiam.product.api.dto.ProductResponse;
import fr.trollgun.optimiam.product.domain.Unit;
import fr.trollgun.optimiam.shopping.domain.ShoppingListItem;
import lombok.Builder;
import lombok.Getter;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Getter
@Builder
public class ShoppingListItemResponse {
    private UUID id;
    private ProductResponse product;
    private BigDecimal requiredQuantity;
    private BigDecimal stockQuantity;
    private BigDecimal missingQuantity;
    private BigDecimal purchasedQuantity;
    private Unit unit;
    private String unitSymbol;
    private boolean checked;
    private boolean autoGenerated;
    private Instant createdAt;
    private Instant updatedAt;

    public static ShoppingListItemResponse from(ShoppingListItem item) {
        if (item == null) return null;
        return ShoppingListItemResponse.builder()
                .id(item.getId())
                .product(ProductResponse.from(item.getProduct()))
                .requiredQuantity(item.getRequiredQuantity())
                .stockQuantity(item.getStockQuantity())
                .missingQuantity(item.getMissingQuantity())
                .purchasedQuantity(item.getPurchasedQuantity())
                .unit(item.getUnit())
                .unitSymbol(item.getUnit() != null ? item.getUnit().getSymbol() : null)
                .checked(item.isChecked())
                .autoGenerated(item.isAutoGenerated())
                .createdAt(item.getCreatedAt())
                .updatedAt(item.getUpdatedAt())
                .build();
    }
}
